Feature/transactions labels
smartvaults/smartvaults-js-client pull request #29
Opened 2023-10-05 20:54 UTC by Dreyhh

Adds getLabeledTransactions to return transactions with Labels 
Adds validation for deletion of vaults with non-zero balance
Adds validation of NIP05

2023-10-05 23:16 UTC, sebastianmontero requested changes
Deberiamos de abstraer el codigo para validar el nip05 a su propio metodo para que lo podamos reutilizar al momento the establecer y obtener el perfil.

2023-10-06 19:39 UTC, sebastianmontero requested changes

2023-10-06 19:39 UTC, sebastianmontero commented on src/SmartVaults.ts
> +  isNip05Verified = async (nip05: string, publicKey: string): Promise<boolean> => {
Creo que tiene mas sentido que esta funcion sea parte de NostrUtil y se importe en SmartVaults y en el metadata handler

2023-10-06 19:39 UTC, sebastianmontero commented on src/event-kind-handler/MetadataHandler.ts
> +  private readonly isNip05Verified: (nip05: string, publicKey: string) => Promise<boolean>
Se deberia de importar de NostrUtil, en lugar de que sea una propiedad de la clase

2023-10-06 20:45 UTC, Dreyhh commented on src/SmartVaults.ts
> +  isNip05Verified = async (nip05: string, publicKey: string): Promise<boolean> => {
done

2023-10-06 20:46 UTC, Dreyhh commented on src/event-kind-handler/MetadataHandler.ts
> +  private readonly isNip05Verified: (nip05: string, publicKey: string) => Promise<boolean>
done

2023-10-06 21:55 UTC, merged