Feature/currency rates
smartvaults/smartvaults-js-client pull request #31
Opened 2023-10-19 19:55 UTC by Dreyhh

Adds support to fetch the current Bitcoin price against some fiat currencies.
 The following properties are added to the BitcoinUtil interface:

-   currency: Map<string, FiatCurrency>
-   bitcoinExchangeRate: Map<FiatCurrency, number> 

 Fiat equivalents are added to the Balance class:

-   confirmedFiat: number
-   immatureFiat: number
-   trustedPendingFiat: number
-   untrustedPendingFiat: number

Adds netFiat property to Transaction details

The following methods are added to the SmartVaults class:

changeFiatCurrency
updateBitcoinExchangeRate

2023-10-20 00:01 UTC, sebastianmontero requested changes

2023-10-20 00:01 UTC, sebastianmontero commented on src/models/PublishedPolicy.ts
> +    if (!this.bitcoinExchangeRate.has(currency)) {
creo que esta logica, de checar si ya hay un exchange rate para el currency especificado y si no llamar al api para obtenerlo deberia de ser abstraído en su propio metodo, probablemente dentro de una clase singleton llamada BitcoinExchangeRate la cual tambien maneje el mapa de currency->rate que se tiene en bitcoinUtil, creo que junto al rate tambien se deberia de mantener el timestamp de cuando se obtuvo el rate, para que  en caso de que sea mas viejo que cierta cantidad de tiempo(propiedad de la clase) también se haga el fetch del rate. Seria bueno que el metodo tambien tuviera un parametro force que en caso de que sea verdadero siempre haga el fetch independientemente de si existe o no. Esta clase tambien puede llevar el registro de cual es el currency activo actualmente.
Que opinas?

2023-10-20 15:45 UTC, Dreyhh commented on src/models/PublishedPolicy.ts
> +    if (!this.bitcoinExchangeRate.has(currency)) {
Me parece bien

2023-10-20 22:02 UTC, sebastianmontero requested changes

2023-10-20 22:02 UTC, sebastianmontero commented on src/models/interfaces.ts
> +  bitcoinExchangeRate: BitcoinExchangeRate
Creo que bitcoinExchangeRate no debe de ser parte de bitcoinUtil, ya que esta interfaz la estamos utilizando para mapear los metodos que vienen de wasm.

2023-10-23 16:36 UTC, Dreyhh commented on src/models/Balance.ts
> +  private convertToFiat(amount: number, unit: string = 'SAT'): number {
done

2023-10-23 16:36 UTC, Dreyhh commented on src/models/interfaces.ts
> +  bitcoinExchangeRate: BitcoinExchangeRate
done

2023-10-23 20:52 UTC, merged